---
title: Introduction
---

### Organization

- 4 credits
- Professors
    - Lectures: Nicolae Cleju
    - Laboratories: Irina Pavel

- Time schedule
    - 14 lectures (2h each)
    - 14 laboratories $\times$ 2h each

- My office hours: *To Be Announced* (best by appointment)


### Evaluation

- Exam = 60%
  - 60% of final grade
  - Exercises and Theory
  - Similar to Information Theory exam

- Laboratory = 40%
  - Laboratory grade: weekly quizzes (+ possibly other announced tests)

- Final grade = 60% Exam + 40% Applications


### Course structure

1. Chapter I:   Random signals
2. Chapter II:  Statistical decision theory
3. Chapter III: Statistical estimation

### Bibliography (TBD)

1. Brown, R. G., Hwang, P. Y. C., Intoduction to random signals and applied Kalman filtering, John Wiley and Sons, Inc., Second Edition, 1992.
1. Garcia, A. L., Probability and random processes for electrical engineering, Addison-Wesley Publishing Company, 1989
1. Munteanu V. Detectie si estimare, Editura "Gh. Asachi" Iasi, 1997.
1. Borda M. E. Teoria transmisiunii informatiei, Partea I-a, Teoria informatiei si codarii (fundamente si aplicatii), Universitatea Tehnica Cluj - Napoca, 1993.
1. Munteanu, V., Teoria transmiterii informatiei, Editura "Gh. Asachi" Iasi, 2001.

### Online access

- Moodle platform: edu.etti.tuiasi.ro
- github.com: https://github.com/nikcleju/DEDP_Course
